name: Update IPs

on:
  schedule:
    - cron: '0 */2 * * *'  # 每两小时运行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run IP Collector
        run: python collect_ips.py
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ips.txt
          git commit -m "Auto update IPs $(date '+%Y-%m-%d %H:%M')" || echo "No changes"
          git push
