name: Update HK IPs

on:
  schedule:
    - cron: '0 */2 * * *'   # 每2小时执行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run IP Collector
        run: python collect_hk_ips.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add hk_ips.txt
          git commit -m "Auto update HK IPs $(date '+%Y-%m-%d %H:%M')" || echo "No changes"
          git push
